name: Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build and test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout branch
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
