name: Docker Image CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
